spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:0/mysql_biao
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8010
mybatis-plus:
  type-aliases-package: com.example.entity
